--SELECT
--	U.NAMESURNAME,U.USERNAME_ ,CT.CITY,TW.TOWN,DS.DISTRICT,A.ADDRESSTEXT,
--	O.ID,O.DATE_,O.TOTALPRICE,P.DATE_,P.APPROVECODE,I.DATE_,I.CARGOFICHENO,
--	IT.ITEMCODE,IT.ITEMNAME,OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL
	
--FROM ORDERS O
--	INNER JOIN USERS U ON U.ID=O.USERID
--	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--	INNER JOIN CITIES CT ON CT.ID=A.CITYID
--	INNER JOIN TOWNS TW ON TW.ID=A.TOWNID
--	INNER JOIN DISTRICTS DS ON DS.ID=A.DISTRICTID
--	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
--	INNER JOIN INVOICES I ON I.ORDERID=O.ID
--	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
--	INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID
--WHERE 
--	U.NAMESURNAME LIKE '%CEYDA GEZ%'

-------------------------------------------------------------------
--SELECT
--	DISTINCT CT.CITY,
--	SUM(OD.LINETOTAL) AS TOPLAMSIPARISTUTARI,
--	SUM(OD.AMOUNT) AS TOPLAMADET,
--	COUNT(OD.ID) AS TOPLAMSAYI
	
--FROM ORDERS O
--	INNER JOIN USERS U ON U.ID=O.USERID
--	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--	INNER JOIN CITIES CT ON CT.ID=A.CITYID
--	INNER JOIN TOWNS TW ON TW.ID=A.TOWNID
--	INNER JOIN DISTRICTS DS ON DS.ID=A.DISTRICTID
--	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
--	INNER JOIN INVOICES I ON I.ORDERID=O.ID
--	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
--	INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID

--GROUP BY CT.CITY
--ORDER BY SUM(OD.LINETOTAL)DESC

---------------------------------------------------------------------



--SELECT
--	IT.CATEGORY1,
--	SUM(OD.LINETOTAL) AS TOPLAMSIPARISTUTARI,
--	SUM(OD.AMOUNT) AS TOPLAMADET,
--	COUNT(OD.ID) AS TOPLAMSAYI,
--	SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) AS ORTALAMABIRIMFIYAT
	
--FROM ORDERS O
--	INNER JOIN USERS U ON U.ID=O.USERID
--	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--	INNER JOIN CITIES CT ON CT.ID=A.CITYID
--	INNER JOIN TOWNS TW ON TW.ID=A.TOWNID
--	INNER JOIN DISTRICTS DS ON DS.ID=A.DISTRICTID
--	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
--	INNER JOIN INVOICES I ON I.ORDERID=O.ID
--	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
--	INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID
----WHERE IT.CATEGORY1='KOZMETIK'
--GROUP BY IT.CATEGORY1
--ORDER BY 5 DESC

------------------------------------------------
--TARÝHE GÖRE
--SELECT
--	CONVERT(DATE,O.DATE_) AS TARIH,SUM(OD.LINETOTAL) AS TOPLAMSIPARISTUTAR,SUM(OD.AMOUNT)AS TOPLAMMIKTAR,COUNT(OD.ID)AS SIPARISSAYISI
	
--FROM ORDERS O
--	INNER JOIN USERS U ON U.ID=O.USERID
--	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--	INNER JOIN CITIES CT ON CT.ID=A.CITYID
--	INNER JOIN TOWNS TW ON TW.ID=A.TOWNID
--	INNER JOIN DISTRICTS DS ON DS.ID=A.DISTRICTID
--	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
--	INNER JOIN INVOICES I ON I.ORDERID=O.ID
--	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
--	INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID
--GROUP BY CONVERT(DATE,O.DATE_)
--ORDER BY CONVERT(DATE,O.DATE_)
---------------------------------------------
--AYLARA GÖRE
--SELECT
--	DATEPART(YEAR,O.DATE_) AS YIL,
--	DATEPART(MONTH,O.DATE_) AS AY,
--	CASE
--		WHEN DATEPART(MONTH,O.DATE_)=1 THEN 'OCAK'
--		WHEN DATEPART(MONTH,O.DATE_)=2 THEN 'SUBAT'
--		WHEN DATEPART(MONTH,O.DATE_)=3 THEN 'MART'
--		WHEN DATEPART(MONTH,O.DATE_)=4 THEN 'NÝSAN'
--		WHEN DATEPART(MONTH,O.DATE_)=5 THEN 'MAYIS'
--		WHEN DATEPART(MONTH,O.DATE_)=6 THEN 'HAZIRAN'
--		WHEN DATEPART(MONTH,O.DATE_)=7 THEN 'TEMMUZ'
--		WHEN DATEPART(MONTH,O.DATE_)=8 THEN 'AGUSTOS'
--		WHEN DATEPART(MONTH,O.DATE_)=9 THEN 'EYLUL'
--		WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKIM'
--		WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASIM'
--		WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARALIK'
--END AS AYADI,

--	SUM(OD.LINETOTAL) AS TOPLAMSIPARISTUTAR,
--	SUM(OD.AMOUNT)AS TOPLAMMIKTAR,
--	COUNT(OD.ID)AS SIPARISSAYISI
	
--FROM ORDERS O
--	INNER JOIN USERS U ON U.ID=O.USERID
--	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--	INNER JOIN CITIES CT ON CT.ID=A.CITYID
--	INNER JOIN TOWNS TW ON TW.ID=A.TOWNID
--	INNER JOIN DISTRICTS DS ON DS.ID=A.DISTRICTID
--	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
--	INNER JOIN INVOICES I ON I.ORDERID=O.ID
--	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
--	INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID
--GROUP BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_)  
--ORDER BY DATEPART(MONTH,O.DATE_),DATEPART(YEAR,O.DATE_)
-----------------------------------------------------------------------

--SELECT
--DATEPART(MONTH,DATE_) AS AY,
--DATEPART(YEAR,DATE_) AS YIL,
--CASE
--	WHEN PAYMENTTYPE=1 THEN 'KREDÝKARTI'
--	WHEN PAYMENTTYPE=2 THEN 'BANKAHAVALESÝ'
--END AS ODEMETURU,
--SUM(PAYMENTS.PAYMENTTOTAL)AS TOPLAMTUTAR
--FROM PAYMENTS
--GROUP BY DATEPART(MONTH,DATE_),DATEPART(YEAR,DATE_),PAYMENTTYPE
--ORDER BY DATEPART(YEAR,DATE_),DATEPART(MONTH,DATE_)

--------------------------------------------------------------------
--SELECT
--	--O.ID AS SIPARISID,
--	--O.DATE_ AS SIPARISTARIHI,
--	--I.DATE_ AS FATURATARIHI,
--	MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS MINSAATFARKI,
--	MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS MAXSAATFARKI,
--	AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_))AS ORTALAMASAATFARKI
	

	
--FROM ORDERS O
--	INNER JOIN USERS U ON U.ID=O.USERID
--	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--	INNER JOIN CITIES CT ON CT.ID=A.CITYID
--	INNER JOIN TOWNS TW ON TW.ID=A.TOWNID
--	INNER JOIN DISTRICTS DS ON DS.ID=A.DISTRICTID
--	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
--	INNER JOIN INVOICES I ON I.ORDERID=O.ID

--ORDER BY DATEDIFF(HOUR,O.DATE_,I.DATE_) ASC	
------------------------------------------------------
--SELECT

--	U.ID,
--	U.NAMESURNAME,
--	AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_))AS ORTALAMATESLIMATSURESÝ,
--	SUM(O.TOTALPRICE) AS TOPLAMSIPARISTUTARI,
--	COUNT(O.ID) AS SIPARISSAYISI,
--	MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS MINTESLIMATSURE,
--    MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS MAXTESLIMATSURE

	
--FROM ORDERS O
--	INNER JOIN USERS U ON U.ID=O.USERID
--	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--	INNER JOIN CITIES CT ON CT.ID=A.CITYID
--	INNER JOIN TOWNS TW ON TW.ID=A.TOWNID
--	INNER JOIN DISTRICTS DS ON DS.ID=A.DISTRICTID
--	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
--	INNER JOIN INVOICES I ON I.ORDERID=O.ID
--GROUP BY U.ID,U.NAMESURNAME
--HAVING AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_))>20
--ORDER BY 4 DESC
------------------------------------------------------------
--SELECT

--	CT.CITY,
--	AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_))AS ORTALAMATESLIMATSURESÝ,
--	SUM(O.TOTALPRICE) AS TOPLAMSIPARISTUTARI,
--	COUNT(O.ID) AS SIPARISSAYISI,
--	MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS MINTESLIMATSURE,
--    MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS MAXTESLIMATSURE

	
--FROM ORDERS O
--	INNER JOIN USERS U ON U.ID=O.USERID
--	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
--	INNER JOIN CITIES CT ON CT.ID=A.CITYID
--	INNER JOIN TOWNS TW ON TW.ID=A.TOWNID
--	INNER JOIN DISTRICTS DS ON DS.ID=A.DISTRICTID
--	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
--	INNER JOIN INVOICES I ON I.ORDERID=O.ID
--GROUP BY CT.CITY
----------------------------------------------------------SUBQUERY--------------------------------------------------
--SELECT
--ITM.ITEMCODE AS URUNKODU,
--ITM.ITEMNAME AS URUNADI,
--(SELECT MIN(ORDERDETAILS.UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENDUSUKFIYAT,
--(SELECT MAX(ORDERDETAILS.UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENYUKSEKFIYAT,
--(SELECT AVG(ORDERDETAILS.UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ORTALAMAFIYAT,
--(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID)  AS TOPLAMADET,
--(
--SELECT TOP 1 DATEPART(MONTH,O.DATE_)AS AY FROM ORDERDETAILS OD 
--INNER JOIN ORDERS O ON OD.ORDERID=O.ID
--WHERE OD.ITEMID=ITM.ID
--GROUP BY DATEPART(MONTH,O.DATE_)
--ORDER BY SUM(AMOUNT) DESC

--) AS ENCOKSATILANAY
--FROM ITEMS ITM
--ORDER BY 3
-------------------------------------------------
--SELECT U.* ,
--(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS  WHERE USERID=U.ID ORDER BY ID DESC ) SONADRES,
--(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS  WHERE USERID=U.ID ORDER BY ID ASC ) ILKADRES
--FROM 
--USERS U
---------------------------------

